//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new planet.
        /// </summary>
        internal static string BuilderString1 {
            get {
                return ResourceManager.GetString("BuilderString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of our world!.
        /// </summary>
        internal static string BuilderString2 {
            get {
                return ResourceManager.GetString("BuilderString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Planet.
        /// </summary>
        internal static string DeletePlanet {
            get {
                return ResourceManager.GetString("DeletePlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Planet.
        /// </summary>
        internal static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Planets.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Planets.
        /// </summary>
        internal static string MainButtonBuilder {
            get {
                return ResourceManager.GetString("MainButtonBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Planets.
        /// </summary>
        internal static string MainButtonCollection {
            get {
                return ResourceManager.GetString("MainButtonCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MainButtonHome {
            get {
                return ResourceManager.GetString("MainButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainButtonSettings {
            get {
                return ResourceManager.GetString("MainButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PlanetDescription {
            get {
                return ResourceManager.GetString("PlanetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galaxy :.
        /// </summary>
        internal static string PlanetGalaxy {
            get {
                return ResourceManager.GetString("PlanetGalaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        internal static string PlanetImagePath {
            get {
                return ResourceManager.GetString("PlanetImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string PlanetName {
            get {
                return ResourceManager.GetString("PlanetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Planet :.
        /// </summary>
        internal static string PlanetSearch {
            get {
                return ResourceManager.GetString("PlanetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Selection :.
        /// </summary>
        internal static string PlanetSelection {
            get {
                return ResourceManager.GetString("PlanetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size :.
        /// </summary>
        internal static string PlanetSize {
            get {
                return ResourceManager.GetString("PlanetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string PlanetSizeKm {
            get {
                return ResourceManager.GetString("PlanetSizeKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Planet :.
        /// </summary>
        internal static string PlanetSorted {
            get {
                return ResourceManager.GetString("PlanetSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System :.
        /// </summary>
        internal static string PlanetSystem {
            get {
                return ResourceManager.GetString("PlanetSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search planet and click by her.
        /// </summary>
        internal static string SearchEditPlanet {
            get {
                return ResourceManager.GetString("SearchEditPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SolarSystem {
            get {
                object obj = ResourceManager.GetObject("SolarSystem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galaxy.
        /// </summary>
        internal static string SortedGalaxy {
            get {
                return ResourceManager.GetString("SortedGalaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortedName {
            get {
                return ResourceManager.GetString("SortedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SortedSize {
            get {
                return ResourceManager.GetString("SortedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SortedSystem {
            get {
                return ResourceManager.GetString("SortedSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string StringLanguage {
            get {
                return ResourceManager.GetString("StringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the World of Planets app!.
        /// </summary>
        internal static string TextBoxHome1 {
            get {
                return ResourceManager.GetString("TextBoxHome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmos in translation from Greek means the world, a structure, a universe..
        /// </summary>
        internal static string TextBoxHome2 {
            get {
                return ResourceManager.GetString("TextBoxHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the expression &quot;fly into space&quot;, &quot;go into space&quot;, &quot;flew into outer space&quot; has long been habitually entered into our lives..
        /// </summary>
        internal static string TextBoxHome3 {
            get {
                return ResourceManager.GetString("TextBoxHome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you want to look at the planets of our universe in offline mode?.
        /// </summary>
        internal static string TextBoxHome4 {
            get {
                return ResourceManager.GetString("TextBoxHome4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have come to the right address!.
        /// </summary>
        internal static string TextBoxHome5 {
            get {
                return ResourceManager.GetString("TextBoxHome5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can compare the size of the planets, the name of the systems and galaxies in which they are located..
        /// </summary>
        internal static string TextBoxHome6 {
            get {
                return ResourceManager.GetString("TextBoxHome6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has the ability to create and edit existing planets..
        /// </summary>
        internal static string TextBoxHome7 {
            get {
                return ResourceManager.GetString("TextBoxHome7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your planets, invent them names, place them in your galaxies..
        /// </summary>
        internal static string TextBoxHome8 {
            get {
                return ResourceManager.GetString("TextBoxHome8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someday the time will come when a person will master the space tightly, and our man will plow through the expanses of the universe, like at home on planet Earth..
        /// </summary>
        internal static string TextBoxHome9 {
            get {
                return ResourceManager.GetString("TextBoxHome9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme :.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin to Create.
        /// </summary>
        internal static string ToCreateButton {
            get {
                return ResourceManager.GetString("ToCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Description.
        /// </summary>
        internal static string ToCreateDescription {
            get {
                return ResourceManager.GetString("ToCreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Galaxy.
        /// </summary>
        internal static string ToCreateGalaxy {
            get {
                return ResourceManager.GetString("ToCreateGalaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Name.
        /// </summary>
        internal static string ToCreateName {
            get {
                return ResourceManager.GetString("ToCreateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet Size.
        /// </summary>
        internal static string ToCreateSize {
            get {
                return ResourceManager.GetString("ToCreateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet System.
        /// </summary>
        internal static string ToCreateSystem {
            get {
                return ResourceManager.GetString("ToCreateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin to Edit.
        /// </summary>
        internal static string ToEditButton {
            get {
                return ResourceManager.GetString("ToEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit planets.
        /// </summary>
        internal static string ToEditString1 {
            get {
                return ResourceManager.GetString("ToEditString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of our world!.
        /// </summary>
        internal static string ToEditString2 {
            get {
                return ResourceManager.GetString("ToEditString2", resourceCulture);
            }
        }
    }
}
